
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/web_day11
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
